version: '3.7'

services:
  puppeteer:
    build: .
    image: puppeteer-chrome-linux
    init: true
    cap_add:
      - SYS_ADMIN
    container_name: puppeteer-chrome
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    working_dir: /app
